#!/bin/bash
#

# 
# readlink for Mac (because Mac readlink does not accept "-f" option)
# 
if [[ $(uname) == *"Darwin"* ]]; then
    function readlink() {
        if [[ $# -gt 1 ]]; then if [[ "$1" == "-f" ]]; then shift; fi; fi
        DIR="$1"; if [[ "$DIR" != *"/"* ]]; then DIR="./$DIR"; fi # 20170228: fixed bug: path without "/"
        DIR=$(echo "${DIR%/*}") # 20160410: fixed bug: source SETUP just under the Softwares dir
        if [[ -d "$DIR" ]]; then cd "$DIR" && echo "$(pwd -P)/$(basename ${1})"; 
        else echo "$(pwd -P)/$(basename ${1})"; fi
    }
fi



# 
# Main program
# 
deploy_current_dir=$(pwd -P)
deploy_script_dir=$(readlink -f $(dirname "${BASH_SOURCE[0]}"))
deploy_upper_dir=$(readlink -f $(dirname "${deploy_script_dir}"))

echo "Welcome"
echo "Deploying SuperDeblending SED fitting files into ${deploy_current_dir} ..."
#sleep 0.25

# 
# Type of fitting
# 
deploy_type="SED"
if [[ $# -ge 1 ]]; then
    deploy_type="$1"
fi

# 
# Copy files
# 
if echo "$deploy_type" | grep -q -i "SED"; then
    cp "${deploy_script_dir}"/base03_3_cost_z02_chab    .
    cp "${deploy_script_dir}"/Chiara_N.sm   .
    cp "${deploy_script_dir}"/clust_models.sm   .
    cp "${deploy_script_dir}"/default_filters.txt   .
    cp "${deploy_script_dir}"/default.sm    .
    cp "${deploy_script_dir}"/do_Galsed .
    cp "${deploy_script_dir}"/do_Galsed.sm  .
    cp "${deploy_script_dir}"/fit_engine.sm .
    cp -r "${deploy_script_dir}"/Magdis    .
    cp "${deploy_script_dir}"/Mullaney_AGN_table3.txt   .
    cp "${deploy_script_dir}"/convert_datatable_for_sed_fitting.sm   .
    date "+%Y-%m-%d %H:%M:%S %Z" > "ReadMe_deploy_files.txt"
    echo "Copied from \"${deploy_script_dir}\"" >> "ReadMe_deploy_files.txt"
    echo "" >> "ReadMe_deploy_files.txt"
fi



