#!/bin/bash
# 
# common caller for dzliu tools:
#=  CrabFitsHeader
#=  CrabFitsImageCrop
#=  CrabPhotAperPhot
#=  CrabPhotRingPhot
#=  CrabTableReadColumn
#=  CrabTableReadInfo
#=  degree2radec
#=  radec2degree
#=  lumdist
# 
# for ff in $(cat CrabFitsHeader | grep "^#= " | tr -s ' ' | cut -d ' ' -f 2); do cp CrabFitsHeader $ff; done
#   
# 
# Linux
if [[ $(uname -s) == Linux ]]; then
    if [[ $(hostname) == planer* || $(hostname) == sapherschel* ]]; then
        # the supercomputer planer has an old GLIBC version 2.5
        $(dirname $0)/ds9_linux_Glibc_2.12/$(basename $0)_linux_x86_64 $*
    else
        $(dirname $0)/ds9_linux_Glibc_2.14/$(basename $0)_linux_x86_64 $*
    fi
fi
# Darwin
if [[ $(uname -s) == Darwin ]]; then
    $(dirname $0)/ds9_mac/$(basename $0)_mac $*
fi
# Cygwin
if [[ $(uname -s) == *CYGWIN* ]]; then
    $(dirname $0)/ds9_cygwin/$(basename $0)_cygwin_x86.exe $*
fi


