#!/bin/bash
#

# 
# readlink for Mac (because Mac readlink does not accept "-f" option)
# 
if [[ $(uname) == *"Darwin"* ]]; then
    function readlink() {
        if [[ $# -gt 1 ]]; then if [[ "$1" == "-f" ]]; then shift; fi; fi
        DIR="$1"; if [[ "$DIR" != *"/"* ]]; then DIR="./$DIR"; fi # 20170228: fixed bug: path without "/"
        DIR=$(echo "${DIR%/*}") # 20160410: fixed bug: source SETUP just under the Softwares dir
        if [[ -d "$DIR" ]]; then cd "$DIR" && echo "$(pwd -P)/$(basename ${1})"; 
        else echo "$(pwd -P)/$(basename ${1})"; fi
    }
fi



# 
# Main program
# 
deploy_current_dir=$(pwd -P)
deploy_script_dir=$(readlink -f $(dirname "${BASH_SOURCE[0]}"))/Galsed_Template

if [[ ! -d "$deploy_script_dir" ]]; then
    echo "Error! Directory is not found: $deploy_script_dir"
    exit 255
fi

echo "Welcome"

while true; do

read -p "Deploying SuperDeblending SED fitting files into the current directory: ${deploy_current_dir}? [y/n] " yn

case $yn in 
    y* ) echo "ok, deploying...";
        break;;
    n* ) echo "ok, exiting...";
        exit;;
    * ) echo "invalid response!";
        continue;;
esac

done

# 
# Copy files
# 
#<20240617># cp "${deploy_script_dir}"/AGN_N.sm   .    # now is do_Galsed.sm
cp "${deploy_script_dir}"/base03_3_cost_z02_chab    .
cp "${deploy_script_dir}"/Chiara_N.sm   .
cp "${deploy_script_dir}"/clust_models.sm   .
cp "${deploy_script_dir}"/default_filters.txt   .
cp "${deploy_script_dir}"/default.sm    .
cp "${deploy_script_dir}"/do_Galsed .
cp "${deploy_script_dir}"/do_Galsed.sm  .
cp "${deploy_script_dir}"/fit_engine.sm .
cp -r "${deploy_script_dir}"/Magdis    .
cp "${deploy_script_dir}"/Mullaney_AGN_table3.txt   .
cp "${deploy_script_dir}"/convert_datatable_for_sed_fitting.sm   .
date "+%Y-%m-%d %H:%M:%S %Z" > "ReadMe_deploy_files.txt"
echo "Copied from \"${deploy_script_dir}\"" >> "ReadMe_deploy_files.txt"
echo "" >> "ReadMe_deploy_files.txt"



