#!/bin/bash
# 

set -e

. do_Preset $*

sm << EOF | tee $DG_FLOG".smlog"
    
    if(   $DG_PARA==0   ){
    #!./do_Cleans
    }
    
    ####################################
    #      PREPARE FIT PARAMETERS      #
    ####################################
    
    #####  EDIT goFine.sm xSet_$DG_IMAX
    macro  read goFine.sm xSet_$DG_IMAX
    
    echo 
    
    ###### EDIT goSimu.sm FixAstrometry for SciFits
    if(    is_file($DG_NAME.fits)   ) {
    define imax_name $DG_NAME
    !echo "We are using "$DG_NAME".fits as the source image."
    !echo " "
    }else {
    !echo "We are using "\$imax_name".fits as the source image. '(The default setting in goFine.sm)'"
    !echo " "
    }
    
    ###### EDIT xdate
    define xdate <"$DG_DATE">
    
    
    
    ######################################
    #      PREPARE FIT WITH CATALOG      #
    ######################################
    
    ####   CATALOG
    define catalog_file \"$DG_CATA\"
    if(    is_file(\$catalog_file)   ) {
    data \$catalog_file
    if(  '$DG_CATA' == 'irac_mips_fluxes_hdfn.dat'  ) {
    read  {idF 3 raF 1 deF 2}
    } else {
    read  {idF 1 raF 2 deF 3}
    }
    !echo " "
    !echo "We are using "\$catalog_file" as the source catalog."
    !echo " "
    }else {
    !echo " "
    !echo "Error! Could not find the source catalog! Please check"\$catalog_file"!"
    !echo " "
    }
    
    ####   EXCLUDE
    define exclude_file "${DG_FSED}.txt"
    if(    is_file(\$exclude_file)    ) {
    data \$exclude_file
    read  {idS 1 raS 2 deS 3 flagExclude 4} # sedMag 9 # <Modified><20140825><DzLIU> #
    set    idF = idF if(flagExclude==0)    set  idIncl = idF   set  idExcl = idS if(flagExclude==1)
    set    raF = raF if(flagExclude==0)    set  raIncl = raF   set  raExcl = raS if(flagExclude==1)
    set    deF = deF if(flagExclude==0)    set  deIncl = deF   set  deExcl = deS if(flagExclude==1)
    !echo "We exclude "\$(sum(flagExclude))" faint sources during the fitting, and only fit "\$(dimen(flagExclude)-sum(flagExclude))" sources."
    !echo " "
    }else {
    !echo "We do not exclude faint sources here."
    !echo " "
    }
    
    ####   INCLUDE
    define include_file "${DG_CATB}"
    if(    is_file(\$include_file)    ) {
    data \$include_file
    read  {idN 1 raN 2 deN 3}
    set    idF = idF concat idN   set  idAdds = idN
    set    raF = raF concat raN   set  raAdds = raN
    set    deF = deF concat deN   set  deAdds = deN
    !echo "We include "\$(dimen(idN))" additional sources selected from the residual maps. "
    !echo "Coordinates are stored in ${DG_CATB}"
    !echo "Now we are fitting "\$(dimen(idF))" sources."
    !echo " "
    }else {
    !echo "We do not include additional sources here."
    !echo " "
    }
    
    ####   TODO: FIT EXCLUDE SOURCES INSTEAD OF INCLUDE SOURCES <Added><20141030><DzLIU>
    if(    2==$DG_PFIT    ) {
    set    idF = idExcl
    set    raF = raExcl
    set    deF = deExcl
    !echo "TODO: Now we do not fit included sources on faint-source-subtracted map, instead we fit excluded sources on fitted-sources-subtracted map!"
    !echo " "
    }
    
    ####   WE NOW HAVE NNNN SOURCES TO FIT
    if(    dimen(idF)>0    ) {
    !echo "We now have "\$(dimen(idF))" sources to be fit."
    !echo " "
    }
    
    
    
    ########################################
    #      PREPARE FIT WITH PRIOR MAG      #
    ########################################
    ####   LOAD PRIOR MAG
    if(    1==$DG_PRIM    ) {
    data  "results_"\$imax"_"\$xdate read < xm\$imax 4 >
    !echo "We are setting prior magnitudes according to the xm"\$imax" in the results_"\$imax"_"\$xdate"."
    !echo " "
    }else {
    !echo "We do not set prior mag for this fit."
    !echo " "
    }
    
    
    
    #################################
    #      PREPARE FIT PARALLEL     #
    #################################
    ####   LOAD PARALLEL
    if(    1==$DG_PARA    ) {
    define doParallel 1
    echo "We are preparing all galfit inputs for later parallel fitting on planer! "
    echo " "
    }
    ###    POST PARALLEL
    if(    2==$DG_PARA    ) {
    define doPostParallel 1
    !echo "We are processing post parallel data now."
    !echo " "
    }
    
    
    
    #####################
    #      GALFIT       #
    #####################
    ###### FIT & REBUILD
    define use_prior_mags $DG_PRIM
    define vary_positions $DG_VARY
    define fix_astrometry 1
    define make_residuals 0
    if(dimen(idF)>0 && $DG_PARA==0) {
    Fit_XXX
    Rebuild_XXX
    }
    if(dimen(idF)>0 && $DG_PARA==1) {
    Fit_XXX
    }
    if(dimen(idF)>0 && $DG_PARA==2) {
    Fit_XXX
    Rebuild_XXX
    }
    
    
    
    ####################
    #      FINISH      #
    ####################
    if(dimen(idF)>0) {
    echo SM Galfit Finished!
    }else {
    echo SM Galfit Failed!
    }
    quit
EOF
# 
sleep 1.0
# 
# do Parallel
#if [[ $DG_PARA == 1 ]]; then
##chmod a+x run*
##echo "cp summary_run boxfits/" >> runpostqsub
##echo "echo Compressing ../doing"$DG_IMAX".boxfits.tar.gz" >> runpostqsub
##echo "tar -c -f ../doing"$DG_IMAX".boxfits.tar -C boxfits ." >> runpostqsub
##echo "gzip      ../doing"$DG_IMAX".boxfits.tar"              >> runpostqsub
##rm       "../doing"$DG_IMAX".box.tar"
##tar -cf  "../doing"$DG_IMAX".box.tar" box* runbox* runqsub runpostqsub summary_run 
##tar -rhf "../doing"$DG_IMAX".box.tar" *.fits
##gzip     "../doing"$DG_IMAX".box.tar"
# 
# <20141028> doing1160 refit galfit to make sure everything is correct
# [@local]
# cd /Users/dliu/Working/2014-CEA/Tool/Level_3_SciData/GalFit/doing1160
# tar -cf ../doing1160.box.galfit.tar summary_run runqsub runpostqsub
# for (( i=0; i<=1000; i++ )); do boxDir=$(printf 'box%d' $i); if [[ -d $boxDir ]]; then echo tar tar -rf ../doing1160.box.galfit.tar $boxDir; tar -rf ../doing1160.box.galfit.tar $boxDir; fi; done
# for (( i=0; i<=1000; i++ )); do boxRun=$(printf 'runbox%d.sh' $i); if [[ -f $boxRun ]]; then echo tar -rf ../doing1160.box.galfit.tar $boxRun; tar -rf ../doing1160.box.galfit.tar $boxRun; fi; done
# gzip ../doing1160.box.galfit.tar
# scp ../doing1160.box.galfit.tar.gz sappcb34:/data/dliu/GoodsNorth/Tool/Level_3_SciData/GalFit/
# scp ../doing1160.box.galfit.tar.gz hubble:~/GOODS-North/
# scp ../do_GalfitRunqsub sappcb34:/data/dliu/GoodsNorth/Tool/Level_3_SciData/GalFit/
# scp ../do_GalfitRunqsub hubble:~/GOODS-North/
# [@planer]
# cd ~/GOODS-North/doing1160/
# tar -xzf ../doing1160.box.galfit.tar.gz
# ../do_GalfitRunqsub 157 159
# [@sappcb34]
# cd /data/dliu/GoodsNorth/Tool/Level_3_SciData/GalFit/doing1160/
# tar -xzf ../doing1160.box.galfit.tar.gz
# ../do_GalfitRunqsub 0 155
# 
#echo "Please do following at local:"
#echo "    scp doing"$DG_IMAX".box.tar.gz dliu@sappcb34:~/Working/2014-CEA/GOODS-North-OPT5600/doing"$DG_IMAX".box.tar.gz"
#echo "then do following at supercomputer:"
#echo "    cd ~/GOODS-North/ && mkdir doing"$DG_IMAX
#echo "    cd doing"$DG_IMAX"/ && tar -xzf ../doing"$DG_IMAX".box.tar.gz"
#echo "    ./runqsub"
#echo "    ./runpostqsub"
#echo "then do following at local:"
#echo "    cd ~/Working/2014-CEA/Tool/Level_3_SciData/GalFit/doing1160"
#echo "    scp dliu@hubble:~/GOODS-North/doing"$DG_IMAX".box.galfit.results.tar.gz ../"
#echo "    tar -xzf ../doing"$DG_IMAX".box.galfit.results.tar.gz -C "$DG_FPWD
#echo 
#fi
# 
sleep 1.0
echo Done!
exit
