#!/bin/bash
# 

set -e

if [[ -z "$SUPERDEBLENDDIR" ]]; then
    source $(dirname "${BASH_SOURCE[0]}")/Softwares/SETUP
fi

. "$SUPERDEBLENDDIR"/do_Preset_DL Galfit $*
# --> this outputs spdb_preset_${DG_IMAX}.sm


sm << EOF | tee "$DG_FLOG.smlog"
    
    ####################################
    #      PREPARE FITTING PARAMS      #
    ####################################
    input spdb_preset_${DG_IMAX}.sm
    data "${DG_CATA}" read {idF 1 raF 2 deF 3}
    
    #####################
    #      GALFIT       #
    #####################
    macro read goFineDL.sm
    if(dimen(idF)>0) {
        Fit_XXX
    }
    if(dimen(idF)>0 && \$doPostParallel>0) {
        Rebuild_XXX
    }
    
    ####################
    #      FINISH      #
    ####################
    if(dimen(idF)>0) {
        echo SM Galfit Finished!
    } else {
        echo SM Galfit Failed!
    }
    
    quit
EOF



