#!/bin/bash
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# Check Superdeblending Softwares
if [[ x"$SUPERDEBLENDDIR" == x"" ]]; then
    echo "Error! Supderdeblending Softwares were not prepared well!"
    echo "Please make sure you have Supderdeblending/Softwares/SETUP"
    echo "and have ran \"source /path/to/Supderdeblending/Softwares/SETUP\""
fi
# 
# 
if [ $# -lt 3 ]; then 
    echo "Usage: $1 16 201407"
    echo "       $1 100 201412 -vary -catalog RadioOwenMIPS24_priors_April18_2014.txt"
    echo "       $1 100 201412 -vary -catalog RadioOwenMIPS24_priors_April18_2014.txt -catalog-add Residual_priors_Band160.txt"
    echo "       $1 160 201407 -vary -priormag"
    echo "       $1 250 201407 -vary -priormag -fitsname goods_north_wdriz_frac0pt6_norm_19dec06_subbackDL"
    echo "       $1 350 201407 -parallel"
    echo "       $1 500 201407 -postparallel"
    echo "       $1 500 201407 -sedpredict SED_predictions_100_201512.txt"
    echo "       $1 1160 201410 -parallel -fitexclude -fitsname spire500_ima_7p2_v0_100615_subfitDL"
    exit
fi
# 
export DG_IMAX=$2
export DG_DATE=$3
export DG_VARY=0
export DG_PRIM=0 # PRIORMAG
export DG_PARA=1 # PARALLEL
export DG_PFIT=0 # fit full catalog? 0=fitAll 1=fitInclSubIncl 2=fitExclSubExcl
export DG_FSED="NONE" # "SED_predictions_goodsn_$1" # _$2
export DG_FRES="NONE"
export DG_CATA="NONE" # "RadioOwenMIPS24_priors_April18_2014.txt"
export DG_CATB="NONE"
export DG_FSCI="NONE"
export DG_FRMS="NONE"
export DG_FPSF="NONE"
export DG_FLOG=$(pwd)'/log_'$1'_'$2'_'$3
export DG_FPWD=`pwd` # Current Path
# 
# Print Date
echo ""
date +"%F %T %Z"
#
# Now check software dependencies on planer
#if [[ $(hostname) == planer* || $(hostname) == sapherschel* ]]; then
#    if [[ -d "/dsm/upgal/data/dliu/Superdeblending/Softwares/" ]]; then 
#        echo ""
#        echo We are running on planer! Loading "/dsm/upgal/data/dliu/Superdeblending/Softwares/SETUP"
#        echo ""
#        source "/dsm/upgal/data/dliu/Superdeblending/Softwares/SETUP"
#    else
#        echo ""
#        echo Warning! "/dsm/upgal/data/dliu/Superdeblending/Softwares/" was not found! "Please make sure you have prepared your own galfit, iraf, sm, wcstools, etc.!"
#        echo ""
#    fi
#fi
echo ""
echo "Checking softwares:"
type galfit
type cl
type sm
type sky2xy
type xy2sky
type CrabPhotAperPhot
echo ""


# 
# Read inputs
# 
while [[ $# -gt 0 ]]; do
    
    case "$1" in
                     
             "-vary") shift
                      DG_VARY=1
                      DG_FSED=$DG_FSED # "_vary"
                      DG_FLOG=$DG_FLOG"_Vary"
                      echo ; echo We are varying prior positions!
                      ;;
                      
         "-priormag") shift
                      DG_PRIM=1
                      DG_FLOG=$DG_FLOG"_PriorMag"
                      ;;
                      
         "-parallel") shift
                      DG_PARA=1
                      DG_FLOG=$DG_FLOG"_Parallel"
                      echo ; echo We are doing parallel!
                      ;;
                      
     "-postparallel") shift
                      DG_PARA=2
                      DG_FLOG=$DG_FLOG"_PostParallel"
                      echo ; echo We are doing post parallel!
                      ;;
                     
          "-catalog") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_CATA="$1"
                          else break; fi; shift
                      done
                      ;;
                     
      "-catalog-inp") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_CATA="$1"
                          else break; fi; shift
                      done
                      ;;
                     
      "-catalog-out") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              GALFIT_CATALOG_OUT="$1"
                          else break; fi; shift
                      done
                      ;;
                     
      "-catalog-add") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_CATB="$1"
                          else break; fi; shift
                      done
                      ;;
                     
      "-sedpredict"*) shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_FSED="$(echo $1 | sed 's/\.txt$//g')"
                          else break; fi; shift
                      done
                      ;;
                     
         "-fitsname") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_FSCI="$(echo $1 | sed 's/\.fits$//g')"
                          else break; fi; shift
                      done
                      ;;
                     
     "-fitsname-sci") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_FSCI="$(echo $1 | sed 's/\.fits$//g')"
                          else break; fi; shift
                      done
                      ;;
                     
     "-fitsname-rms") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_FRMS="$(echo $1 | sed 's/\.fits$//g')"
                          else break; fi; shift
                      done
                      ;;
                     
     "-fitsname-psf") shift
                      while [[ $# -gt 0 ]]; do
                          if [[ "$1" != "-"* ]]; then
                              DG_FPSF="$(echo $1 | sed 's/\.fits$//g')"
                          else break; fi; shift
                      done
                      ;;
                     
           "-fitall") shift
                      DG_PFIT=0
                      DG_FLOG=$DG_FLOG"_FitALL"
                      ;;
                     
          "-fitincl") shift
                      DG_PFIT=1
                      DG_FLOG=$DG_FLOG"_FitIncl"
                      ;;
                     
          "-fitexcl") shift
                      DG_PFIT=2
                      DG_FLOG=$DG_FLOG"_FitExcl"
                      ;;
                     
          "-fitadds") shift
                      #DG_CATB="Radec_of_new_priors.txt"
                      DG_FLOG=$DG_FLOG"_FitAdds"
                      ;;
                      
                   *) shift
                   
    esac
done
# 
if [[ x"$DG_CATA" != x"NONE" ]]; then
    if [ -f $DG_CATA ]; then
        echo ; echo "We are using catalog $DG_CATA"
    else
        echo ; echo "Error! Catalog file $DG_CATA does not exist! Abort!"; exit 1
    fi
else 
    echo ; echo "Error! We have no catalog!"; exit 1
fi
# 
if [[ x"$DG_FSCI" != x"NONE" ]]; then
    if [ -f $DG_FSCI.fits ]; then
        echo ; echo "We are using map $DG_FSCI.fits instead of the map in goFine.sm"
    else
        echo ; echo "Error! Fits file $DG_FSCI.fits does not exist! Abort!"; exit 1
    fi
else
    echo ; echo "We do not set fitsname-sci and will use the default sci fits image!"
fi
# 
if [[ x"$DG_FRMS" != x"NONE" ]]; then
    if [ -f $DG_FRMS.fits ]; then
        echo ; echo "We are using map $DG_FRMS.fits instead of the map in goFine.sm"
    else
        echo ; echo "Error! Fits file $DG_FRMS.fits does not exist! Abort!"; exit 1
    fi
else
    echo ; echo "We do not set fitsname-rms and will use the default rms fits image!"
fi
# 
if [[ x"$DG_FPSF" != x"NONE" ]]; then
    if [ -f $DG_FPSF.fits ]; then
        echo ; echo "We are using map $DG_FPSF.fits instead of the map in goFine.sm"
    else
        echo ; echo "Error! Fits file $DG_FPSF.fits does not exist! Abort!"; exit 1
    fi
else
    echo ; echo "We do not set fitsname-psf and will use the default psf fits image!"
fi
# 
if [[ x"$DG_CATB" != x"NONE" ]]; then
    if [[ -f $DG_CATB ]]; then
        echo ; echo "We will fit additional objects in $DG_CATB!"
    else
        echo ; echo "Error! Additonal catalog $DG_CATB does not exist! Abort!"; exit 1
    fi
else
    echo ; echo "We do not set any additonal catalog!"
fi
# 
if [[ $DG_PFIT -gt 0 ]]; then
    if [[ -f $DG_FSED.txt ]]; then
        echo ; echo "We are using SED prediction $DG_FSED.txt"
        if [[ $DG_PFIT -eq 1 && x"$DG_CATB" == x ]]; then echo ; echo We are fitting included objects only!; fi
        if [[ $DG_PFIT -eq 1 && x"$DG_CATB" != x ]]; then echo ; echo We are fitting included objects and additional objects only!; fi
        if [[ $DG_PFIT -eq 2 && x"$DG_CATB" == x ]]; then echo ; echo We are fitting excluded objects only!; fi
        if [[ $DG_PFIT -eq 2 && x"$DG_CATB" != x ]]; then echo ; echo We are fitting excluded objects only!; fi #<TODO># adds
    else
        echo ; echo "Error! SED prediction file $DG_FSED.txt does not exist! Abort!"; exit 1
    fi
else 
    echo ; echo "We will fit all catalog objects!"
fi
# 
echo ; echo "We will log into $DG_FLOG.smlog"
# 
# more -- checking files
if [[ ! -f "goFine.sm" ]]; then ln -fs "../goFine.sm"; fi
if [[ ! -f "goSimu.sm" ]]; then ln -fs "../goSimu.sm"; fi
# if [[ ! -f "run_image_util.sm" ]]; then ln -fs "../run_image_util.sm"; fi
# if [[ ! -f "run_update_catalog.sm" ]]; then ln -fs "../run_update_catalog.sm"; fi
# 





