#!/bin/bash
#
#${BASH_SOURCE[0]}
#
# Linux
if [[ $(uname -s) == Linux ]]; then
    if [[ $(hostname) == planer* || $(hostname) == sapherschel* ]]; then
        # the supercomputer planer has an old GLIBC version 2.5
        $(dirname $(readlink -f $0))/galfit_linux_Glibc_2.12/galfit3rhel $*
    else
        $(dirname $(readlink -f $0))/galfit_linux_Glibc_2.14/galfit3redhat $*
    fi
fi
# Darwin
if [[ $(uname -s) == Darwin ]]; then
    $(dirname $0)/galfit_mac/galfit $*
fi

