#!/bin/bash
#
#${BASH_SOURCE[0]}
#
# Linux
if [[ $(uname -s) == Linux ]]; then
    if [[ $(bc <<< "$(ldd --version | head -n 1 | tr -s ' ' | cut -d ' ' -f 4 | cut -d '.' -f 2)<14") -eq 1 ]]; then
        # the supercomputer planer has an old GLIBC version 2.5
        $(dirname $(readlink -f $0))/galfit_linux_Glibc_2.12/galfit3rhel255 -imax 1000 $*
    else
        $(dirname $(readlink -f $0))/galfit_linux_Glibc_2.14/galfit3redhat255 -imax 1000 $*
    fi
fi
# Darwin
if [[ $(uname -s) == Darwin ]]; then
    $(dirname $0)/galfit_mac/galfit255 -imax 1000 $*
fi

