#!/bin/bash
#
#${BASH_SOURCE[0]}
#
# Linux
if [[ $(uname -s) == Linux ]]; then
    if [[ $(hostname) == planer* ]]; then
        # the supercomputer planer has an old GLIBC version 2.5
        $(dirname $(readlink -f $0))/galfit_linux_Glibc_2.12/galfit3rhel255 -imax 1000 $*
    else
        $(dirname $(readlink -f $0))/galfit_linux_Glibc_2.14/galfit3redhat255 -imax 1000 $*
    fi
fi
# Darwin
if [[ $(uname -s) == Darwin ]]; then
    $(dirname $0)/galfit_mac/galfit255 -imax 1000 $*
fi

