#!/bin/bash
# 

if [[ $# -lt 1 ]]; then
    echo "Usage: iraf_cl_exec_file \"file.cl\""
    exit
fi

if [[ $(type cl 2>/dev/null | wc -l) -gt 0 ]]; then
    cl -old < $1 >> /dev/null 2>&1
elif [[ $(type irafcl 2>/dev/null | wc -l) -gt 0 ]]; then
    irafcl -c -f $1
else
    echo "Error! cl or irafcl is not executable?!"
    exit 255
fi


