#!/bin/bash
# <TODO> can not support --include --exclude ... --> can only sync entire dir1 to dir2.
# <TODO> now only support one name pattern!
if [[ $# -lt 2 ]]; then echo Usage: rsyncdir dir1 dir2 ["IncludeNamePattern" ["IncludeNamePattern2" ["IncludeNamePattern3"]]]; exit; fi
# 
rsyncdir_rargs=("$@")
rsyncdir_rexec="do_rsync_dirs.sh"
rsyncdir_relog="do_rsync_dirs.log"
rsyncdir_rdssh=$(echo "$1" "$2" | grep ':' | wc -l) # use ssh if dir contains :
rsyncdir_rdir2=$(echo "$2" | sed -e 's/.*://g')
rsyncdir_rsync="mkdir -p $rsyncdir_rdir2 && rsync --delete" # we will create remote dir if not exists <TODO> should not contain white space!!!

# <TODO> mkdir -p permission problem
# for (( rsyncdir_i = 1; rsyncdir_i < $#; rsyncdir_i++ )); do
#     # echo ${rsyncdir_rargs[$rsyncdir_i]}
#     if [[ "${rsyncdir_rargs[$rsyncdir_i]}" == "--rsync-path="* ]]; then
#         rsyncdir_rsync=$(echo "${rsyncdir_rargs[$rsyncdir_i]}" | sed -e 's/--rsync-path=//g')
#     fi
# done
# echo $rsyncdir_rsync
# exit

# 
if [[ $# -eq 2 && $rsyncdir_rdssh -eq 0 ]]; then # use namepattern
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"*\" --include=\"*/*\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"*\" --include=\"*/*\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzt --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include='*' --include='*/*' --exclude='*' "$1/" "$2/" --dry-run
fi
if [[ $# -eq 2 && $rsyncdir_rdssh -eq 1 ]]; then # use namepattern
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"*\" --include=\"*/*\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"*\" --include=\"*/*\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzte ssh --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include='*' --include='*/*' --exclude='*' "$1/" "$2/" --dry-run
fi
# 
if [[ $# -eq 3 && $rsyncdir_rdssh -eq 0 ]]; then # use namepattern
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzt --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include="$3" --exclude='*' "$1/" "$2/" --dry-run
fi
if [[ $# -eq 3 && $rsyncdir_rdssh -eq 1 ]]; then # use namepattern
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzte ssh --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include="$3" --exclude='*' "$1/" "$2/" --dry-run
fi
# 
if [[ $# -eq 4 && $rsyncdir_rdssh -eq 0 ]]; then # use namepattern
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzt --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include="$3" --include="$4" --exclude='*' "$1/" "$2/" --dry-run
fi
if [[ $# -eq 4 && $rsyncdir_rdssh -eq 1 ]]; then # use namepattern
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzte ssh --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include="$3" --include="$4" --exclude='*' "$1/" "$2/" --dry-run
fi
# 
if [[ $# -eq 5 && $rsyncdir_rdssh -eq 0 ]]; then # use namepattern
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --include=\"$5\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzt --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --include=\"$5\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzt --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include="$3" --include="$4" --include="$5" --exclude='*' "$1/" "$2/" --dry-run
fi
if [[ $# -eq 5 && $rsyncdir_rdssh -eq 1 ]]; then # use namepattern
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --include=\"$5\" --exclude=\"*\" \"$1/\" \"$2/\"  > "$rsyncdir_rexec"
    echo rsync -vrhlmzte ssh --rsync-path=\"$rsyncdir_rsync\" --checksum --exclude=\"$rsyncdir_rexec\" --exclude=\"*~\" --exclude=\".*\" --include=\"$3\" --include=\"$4\" --include=\"$5\" --exclude=\"*\" \"$1/\" \"$2/\"  --dry-run
         rsync -vrhlmzte ssh --rsync-path="$rsyncdir_rsync" --checksum --exclude="$rsyncdir_rexec" --exclude="*~" --exclude=".*" --include="$3" --include="$4" --include="$5" --exclude='*' "$1/" "$2/" --dry-run
fi
echo 
echo 
echo -n "We are about to modify the files, OK? [y/n] "
read rsyncdir_exec
#     $(echo $rsyncdir_exec | grep -i -e '^y' | wc -l) == 1 not working!
if [[ $(echo $rsyncdir_exec | grep -i -e '^y' | wc -l) -eq 1 ]]; then
    echo 
    echo 
    cat      "$rsyncdir_rexec"
    chmod +x "$rsyncdir_rexec"
           ./"$rsyncdir_rexec"  |  tee "$rsyncdir_relog"
    echo 
    echo Done! 
    echo You might want to check or delete temporary files: "$rsyncdir_rexec" "$rsyncdir_relog"
    echo 
else
    echo 
    echo 
    echo Abort! We have not change anything. 
    rm "$rsyncdir_rexec"
    echo 
fi

