#!/bin/bash
#
#${BASH_SOURCE[0]}
#
# Linux
if [[ $(uname -s) == Linux ]]; then
    if [[ $(bc <<< "$(ldd --version | head -n 1 | tr -s ' ' | cut -d ' ' -f 4 | cut -d '.' -f 2)<14") -eq 1 ]]; then
        # the supercomputer planer has an old GLIBC version 2.5
        $(dirname $(readlink -f $0))/sextractor_linux_Glibc_2.12/sex $*
    else
        $(dirname $(readlink -f $0))/sextractor_linux_Glibc_2.14/sex $*
    fi
fi
# Darwin
if [[ $(uname -s) == Darwin ]]; then
    $(dirname $0)/sextractor_mac/sex $*
fi

