#!/bin/bash
#

type readlink > /dev/null
type dirname > /dev/null

# 
# sm in system path
SMPATHS=$(echo $PATH | sed -e "s%$(dirname $(readlink -f $0)):%%g")
SMEXECS=$(bash -c "PATH=$SMPATHS; type sm 2>/dev/null;" | sed -e 's%sm is %%g')
SMDATES=$(date +%s.$(date +%N|cut -b 1,2,3,4)) # SMDATE=$(date +%Y%m%d.%H%M%S.%N.%Z)

#
# Linux
if [[ $(uname -s) == Linux ]]; then
    if [[ $(hostname) == planer* || $(hostname) == sapherschel* ]]; then
        # the supercomputer planer has an old GLIBC version 2.5
        if [[ "$SMEXECS"x != ""x ]]; then ln -fs $SMEXECS \
           $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.12/bin/sm; fi
           $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.12/bin/sm_portable $*
        rm $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.12/bin/sm
    else
        if [[ "$SMEXECS"x != ""x ]]; then ln -fs $SMEXECS \
           $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.14/bin/sm; fi
           $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.14/bin/sm_portable $*
        rm $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.14/bin/sm
    fi
fi
#
# Darwin
if [[ $(uname -s) == Darwin ]]; then
        if [[ "$SMEXECS"x != ""x ]]; then ln -fs $SMEXECS \
           $(dirname $(readlink -f $0))/Supermongo_mac_10.8.2/bin/sm; fi
           $(dirname $(readlink -f $0))/Supermongo_mac_10.8.2/bin/sm_portable $*
        rm $(dirname $(readlink -f $0))/Supermongo_mac_10.8.2/bin/sm
fi



