#!/bin/bash
#

#
# readlink for Mac (because Mac readlink does not accept "-f" option)
if [[ $(uname) == *"Darwin"* ]]; then
    function readlink() {
        if [[ $# -gt 1 ]]; then if [[ "$1" == "-f" ]]; then shift; fi; fi
        DIR=$(echo "${1%/*}"); (cd "$DIR" && echo "$(pwd -P)/$(basename ${1})")
    }
fi

type readlink > /dev/null
type dirname > /dev/null

# 
# sm in system path
SMPATHS=$(echo $PATH | sed -e "s%$(dirname $(readlink -f $0)):%%g")
SMEXECS="" #<TODO># $(bash -c "PATH=$SMPATHS; type sm 2>/dev/null;" | sed -e 's%sm is %%g')
SMDATES=$(date +%s.$(date +%N|cut -b 1,2,3,4)) # SMDATE=$(date +%Y%m%d.%H%M%S.%N.%Z)

#
# Linux
if [[ $(uname -s) == Linux ]]; then
    if [[ $(bc <<< "$(ldd --version | head -n 1 | tr -s ' ' | cut -d ' ' -f 4 | cut -d '.' -f 2)<14") -eq 1 ]]; then
        # the supercomputer planer has an old GLIBC version 2.5
        if [[ "$SMEXECS"x != ""x ]]; then ln -fs $SMEXECS $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.12/bin/sm; fi
                                                           $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.12/bin/sm_portable $*
        if [[ "$SMEXECS"x != ""x ]]; then              rm $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.12/bin/sm; fi
    else
        if [[ "$SMEXECS"x != ""x ]]; then ln -fs $SMEXECS $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.14/bin/sm; fi
                                                           $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.14/bin/sm_portable $*
        if [[ "$SMEXECS"x != ""x ]]; then              rm $(dirname $(readlink -f $0))/Supermongo_linux_Glibc_2.14/bin/sm; fi
    fi
fi
#
# Darwin
if [[ $(uname -s) == Darwin ]]; then
        if [[ "$SMEXECS"x != ""x ]]; then ln -fs $SMEXECS $(dirname $(readlink -f $0))/Supermongo_mac_10.8.2/bin/sm; fi
                                                           $(dirname $(readlink -f $0))/Supermongo_mac_10.8.2/bin/sm_portable $*
        if [[ "$SMEXECS"x != ""x ]]; then              rm $(dirname $(readlink -f $0))/Supermongo_mac_10.8.2/bin/sm; fi
fi



