#!/bin/bash
# Linux
if [[ $(uname -s) == Linux ]]; then
    $(dirname $0)/galfit_linux/galfit3redhat255 $*
fi
# Darwin
if [[ $(uname -s) == Darwin ]]; then
    $(dirname $0)/galfit_mac/galfit255 $*
fi

